// Maps known item names (as they appear in the "Item Description" column) to a
// category. This exists because the Smartsheet has no Category column of its
// own — used as a fallback in lib/smartsheet.js so the category filter works.

const CATEGORY_ITEMS = {
  'Office Supplies': [
    'AA Duracell Batteries',
    'AAA Duracell Batteries',
    'D Duracell Batteries',
    '3V Duracell Batteries',
    '9V Duracell Batteries',
    'Rubber Bands',
    'Super Glue',
    'Duct Tape',
    'Packing Tape',
    'Invisible Regular Tape',
    'Double-Sided Scotch Tape',
    'Correction Tape',
    '1.5 × 2 Small Post-it Notes',
    '2 × 2 Small Post-it Notes',
    '3 × 3 Medium Post-it Notes',
    'Post-it Flags',
    'Black EasyTouch Pens',
    'Blue EasyTouch Pens',
    'Red EasyTouch Pens',
    'Mechanical Pencils',
    'Pink Universal Highlighters',
    'Blue Highlighters',
    'Yellow BIC Brite Liner',
    'Pink BIC Brite Liner',
    'Green Highlighters',
    'Blue Sharpie Markers',
    'Black Sharpie Markers',
    'Red Sharpie Markers',
    'Blue Expo Markers',
    'Black Expo Markers – Thin',
    'Black Expo Markers – Chisel',
    'Red Expo Markers',
    'Green Expo Markers',
    'Purple Expo Markers',
    'Expo Dry Erasers',
    'Scissors',
    'Large 3-Hole Punch',
    'Heavy-Duty Stapler',
    'Stapler',
    'Staple Remover',
    'Regular Staples',
    'Heavy-Duty Staples',
    'Small Binder Clips',
    'Medium Binder Clips',
    'Large Binder Clips',
    'Small Paper Clips',
    'Large Paper Clips',
    'Push Pins',
    '8 × 5 Cambridge Notebooks – Small, for Notes',
    '8.5 × 11 Cambridge Notebooks – Meeting Minutes',
    '8.25 × 11 Cambridge Notebooks – Notes',
    'Brother Laminated Tape – Black on White Labels',
    'Brothers Laminated Tape – Black on White Labels',
    'Optiazure Laminating Pouches',
    'Blank Envelopes',
    'UHD Envelopes',
    'UHD Letterheads',
    'Fax Coversheets',
    'Large White Folders',
    'Manila Folders',
    'White Dividers – Write-On',
    'Print & Apply Dividers – Clear',
    'Color-Coding Labels',
    'Sheet Protectors',
    'Kleenex',
    'Lysol Spray',
    'Masks',
    'Hand Sanitizer',
    'Lanyards',

    // Aliases matching the exact spelling/formatting used in the live Smartsheet.
    '1.5 x 2 (Small) Post it',
    '2 x 2 (Small) Post it',
    '3 x 3 (Medium) Post it',
    'Sign Post it (Flags)',
    'Black Easy Touch Pens',
    'Blue Easy Touch Pens',
    'Red Easy Touch Pens',
    'Pink Universal Highlight',
    'Black Expo Markers thin',
    'Black Expo Markers chisel',
    'Heavy Duty Stapler',
    'Heavy Duty Staples',
    '8 x 5 Cambridge Notebooks - Small for Notes',
    '8.5 x 11 Cambridge Notebooks - Meeting Minutes',
    '8.25 x 11 Cambridge Notebooks - Notes',
    'Brother Laminated Tape - Black on White Labels',
    'Brothers Laminated Tape - Black on White Labels',
    'White Dividers - Write On',
    'Print & Apply Dividers - Clear',
    'Color Coding Labels',
  ],
  'Breakroom Supplies': [
    'Refrigerator Air Filter',
    'Refrigerator Water Filter',
    'Coffee Maker Water Filter',
    'Gloves',
    'Boardwalk Forks',
    'Boardwalk Spoons',
    'Boardwalk Knives',
    'Bowls',
    '6-inch Plates',
    '9-inch Plates',
    'Folgers Coffee',
    'Original Creamer Powder',
    'Original Creamer Packets – S821',
    'Hazelnut Creamer Pods – S821',
    'Hazelnut Liquid Pumps',
    'French Vanilla Liquid Pumps',
    'Coffee Filters',
    'Coffee Stir Sticks',
    'Sweet’N Low',
    'Truvia',
    'Sugar',
    'Salt',
    'Pepper',
    'Swiss Miss Hot Chocolate',
    'Earl Grey Black Tea',
    'Green Tea',
    'Lemon & Ginger Tea',
    'Cups',
    'Multi-Fold Paper Towels',
    'Bounty Paper Towel Rolls',
    'Dawn Dish Detergent',
    'Lysol/Clorox Wipes',
    'Purell Hand Sanitizer Refills',
    'Scott Hand Soap Refills',
    'Dish Sponges',

    // Aliases matching the exact spelling/formatting used in the live Smartsheet.
    '6" Plates',
    '9" Plates',
    'Original Creamer packets S821',
    'Hazelnut Creamer pods for S821',
    'Coffee Stir Stix',
    'Sweet N Low',
    'Earl Grey - Black Tea',
    'Bounty Paper Towel Roll',
    'Dawn Soap Detergent',
    'Lysol Wipes/ Clorox Wipes',
  ],
};

const ITEM_TO_CATEGORY = {};
for (const [category, items] of Object.entries(CATEGORY_ITEMS)) {
  for (const item of items) {
    ITEM_TO_CATEGORY[item.trim().toLowerCase()] = category;
  }
}

/** Look up the category for an item name (case-insensitive), or null if unknown. */
export function getCategoryForItem(name) {
  if (!name) return null;
  return ITEM_TO_CATEGORY[String(name).trim().toLowerCase()] ?? null;
}
